### ISSUE TITLE
some platforms need to link in `librt` for clock C stubs

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage-clock#8]
See https://travis-ci.org/mirage/mirage-skeleton/jobs/154153008#L687 and http://stackoverflow.com/questions/2418157/ubuntu-linux-c-error-undefined-reference-to-clock-gettime-and-clock-settim .

**Comment by dbuenzli** [comment]
AFAIK it's only on linux. You can have a look at the way it's done in ptime and mtime: 

https://github.com/dbuenzli/ptime/blob/master/myocamlbuild.ml
https://github.com/dbuenzli/mtime/blob/master/myocamlbuild.ml
